name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_MINIMUM_RELEASE_AGE: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true
          cache_dependency_path: pnpm-lock.yaml
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Pack
        run: |
          mkdir -p tmp/npm
          pnpm pack --pack-destination tmp/npm
          mv tmp/npm/*.tgz tmp/npm/package.tar.gz

      - name: Publish to npm
        run: npm publish tmp/npm/package.tar.gz --provenance --access public

      - name: Publish Release Asset
        uses: softprops/action-gh-release@v3
        with:
          files: tmp/npm/package.tar.gz
